# Generated by Django 3.2 on 2023-05-04 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='classifieralgorithm',
            name='code',
        ),
        migrations.RemoveField(
            model_name='classifieralgorithm',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient_id', models.CharField(max_length=255)),
                ('input_data', models.CharField(max_length=10000)),
                ('response_data', models.CharField(max_length=10000)),
                ('feedback_response', models.CharField(blank=True, max_length=10000, null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='api.endpoint')),
            ],
        ),
        migrations.AddField(
            model_name='classifieralgorithm',
            name='endpoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifier_algorithms', to='api.endpoint'),
        ),
    ]
