# Generated by Django 3.2.19 on 2023-06-21 02:28

import backend.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230504_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='classifieralgorithm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='request',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='classifieralgorithm',
            name='id',
            field=models.CharField(db_index=True, default=backend.utils.get_new_id, max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='id',
            field=models.CharField(db_index=True, default=backend.utils.get_new_id, max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='request',
            name='id',
            field=models.CharField(db_index=True, default=backend.utils.get_new_id, max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
