# Generated by Django 3.2.19 on 2023-06-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230621_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifieralgorithm',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='classifieralgorithm',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
