version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile_python
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - .:/backend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile_vue
    ports:
      - "8080:8080"
