version: "3"

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: risk_calculator_db
      POSTGRES_USER: risk_calculator_user
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - risk_calculator_network
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: >
      bash -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    container_name: backend
    volumes:
      - ./backend:/backend
      - ./config/.env:/code/.env
    environment:
      DB_NAME: risk_calculator_db
      DB_USER: risk_calculator_user
      DB_PASSWORD: 1234
      DB_HOST: localhost

    networks:
      - risk_calculator_network
    restart: always

  frontend:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    container_name: frontend
    ports:
      - "8080:8080"
    networks:
      - risk_calculator_network
    restart: always

networks:
  risk_calculator_network:
    driver: bridge
