version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: >
      bash -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    container_name: backend
    volumes:
      - ./backend:/backend
      - ./config/.env:/code/.env
    environment:
      DB_NAME: risk_calculator_db
      DB_USER: risk_calculator_user
      DB_PASSWORD: 1234
      DB_HOST: localhost

    network_mode: host
    restart: always

  frontend:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    container_name: frontend
    ports:
      - "8080:8080"

    restart: always
